# Generated by Django 2.2.7 on 2019-12-04 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_name', models.CharField(max_length=128, unique=True, verbose_name='办公用品名称')),
                ('specs', models.CharField(max_length=255, null=True, verbose_name='办公用品规格')),
                ('remarks', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '办公用品信息',
                'verbose_name_plural': '办公用品信息',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='部门名称', max_length=50, verbose_name='名称')),
                ('label', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='标签')),
                ('remarks', models.CharField(blank=True, max_length=155, null=True, verbose_name='备注')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent_dept_id', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.Department', verbose_name='上级部门id')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Warehousing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehousing_num', models.IntegerField(default=1, verbose_name='入库数量')),
                ('warehousing_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入库时间')),
                ('warehousing_update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remarks', models.CharField(max_length=255, null=True, verbose_name='入库备注')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Articles', verbose_name='用品名称')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
                'ordering': ['-warehousing_date'],
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱地址')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('is_leader', models.BooleanField(default=False, verbose_name='领导')),
                ('is_active', models.BooleanField(default=True, verbose_name='已激活')),
                ('is_admin', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.LoginUser', verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.Department')),
            ],
            options={
                'verbose_name': '登录用户',
                'verbose_name_plural': '登录用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='ExWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_warehouse_num', models.IntegerField(default=1, verbose_name='出库数量')),
                ('ex_warehouse_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='出库时间')),
                ('ex_warehouse_update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.IntegerField(choices=[(1, '生成出库'), (2, '确认出库'), (3, '驳回出库')], default=1, verbose_name='出库状态')),
                ('status_label', models.CharField(max_length=255, null=True, verbose_name='说明(状态补充说明)')),
                ('remarks', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Articles', verbose_name='用品名称')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_user', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.Department')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_user', to=settings.AUTH_USER_MODEL, verbose_name='领用人')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validator_user', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
                'ordering': ['-ex_warehouse_date'],
            },
        ),
    ]
