# Generated by Django 2.2.7 on 2019-12-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.LoginUser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='exwarehouse',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_user', to='register.LoginUser', verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='exwarehouse',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_user', to='register.LoginUser', verbose_name='领用人'),
        ),
        migrations.AlterField(
            model_name='exwarehouse',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validator_user', to='register.LoginUser', verbose_name='确认人'),
        ),
        migrations.AlterField(
            model_name='warehousing',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.LoginUser', verbose_name='创建人'),
        ),
    ]
