# Generated by Django 2.2.7 on 2019-12-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20191206_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exwarehouse',
            name='requisition',
            field=models.CharField(default=None, max_length=128, verbose_name='领用人'),
        ),
    ]
